-- Candidate SQL for isolated testing; not deployed or registered as a migration.
BEGIN;
SET LOCAL lock_timeout = '5s';
REVOKE ALL PRIVILEGES ON TABLE public.books FROM anon, authenticated;
ALTER TABLE public.books ENABLE ROW LEVEL SECURITY;
DROP POLICY "public read" ON public.books;
GRANT SELECT ON TABLE public.books TO anon, authenticated;
CREATE POLICY "pilot trusted read" ON public.books FOR SELECT TO anon, authenticated USING (status = 'active');
REVOKE ALL PRIVILEGES ON TABLE public.inquiry_lens_annotations FROM anon, authenticated;
ALTER TABLE public.inquiry_lens_annotations ENABLE ROW LEVEL SECURITY;
DROP POLICY "public read" ON public.inquiry_lens_annotations;
GRANT SELECT ON TABLE public.inquiry_lens_annotations TO anon, authenticated;
CREATE POLICY "pilot trusted read" ON public.inquiry_lens_annotations FOR SELECT TO anon, authenticated USING (status IN ('teacher_reviewed','teacher_added') AND EXISTS (SELECT 1 FROM public.books b WHERE b.id = inquiry_lens_annotations.book_id AND b.status = 'active'));
REVOKE ALL PRIVILEGES ON TABLE public.inquiry_lenses FROM anon, authenticated;
ALTER TABLE public.inquiry_lenses ENABLE ROW LEVEL SECURITY;
DROP POLICY "public read" ON public.inquiry_lenses;
GRANT SELECT ON TABLE public.inquiry_lenses TO anon, authenticated;
CREATE POLICY "pilot trusted read" ON public.inquiry_lenses FOR SELECT TO anon, authenticated USING (true);
REVOKE ALL PRIVILEGES ON TABLE public.pride_value_annotations FROM anon, authenticated;
ALTER TABLE public.pride_value_annotations ENABLE ROW LEVEL SECURITY;
DROP POLICY "public read" ON public.pride_value_annotations;
GRANT SELECT ON TABLE public.pride_value_annotations TO anon, authenticated;
CREATE POLICY "pilot trusted read" ON public.pride_value_annotations FOR SELECT TO anon, authenticated USING (status IN ('teacher_reviewed','teacher_added') AND EXISTS (SELECT 1 FROM public.books b WHERE b.id = pride_value_annotations.book_id AND b.status = 'active'));
REVOKE ALL PRIVILEGES ON TABLE public.pride_values FROM anon, authenticated;
ALTER TABLE public.pride_values ENABLE ROW LEVEL SECURITY;
DROP POLICY "public read" ON public.pride_values;
GRANT SELECT ON TABLE public.pride_values TO anon, authenticated;
CREATE POLICY "pilot trusted read" ON public.pride_values FOR SELECT TO anon, authenticated USING (true);
REVOKE ALL PRIVILEGES ON TABLE public.reading_strategies FROM anon, authenticated;
ALTER TABLE public.reading_strategies ENABLE ROW LEVEL SECURITY;
DROP POLICY "public read" ON public.reading_strategies;
GRANT SELECT ON TABLE public.reading_strategies TO anon, authenticated;
CREATE POLICY "pilot trusted read" ON public.reading_strategies FOR SELECT TO anon, authenticated USING (true);
REVOKE ALL PRIVILEGES ON TABLE public.reading_strategy_annotations FROM anon, authenticated;
ALTER TABLE public.reading_strategy_annotations ENABLE ROW LEVEL SECURITY;
DROP POLICY "public read" ON public.reading_strategy_annotations;
GRANT SELECT ON TABLE public.reading_strategy_annotations TO anon, authenticated;
CREATE POLICY "pilot trusted read" ON public.reading_strategy_annotations FOR SELECT TO anon, authenticated USING (status IN ('imported_teacher','imported_ozlit','teacher_reviewed','teacher_added') AND EXISTS (SELECT 1 FROM public.books b WHERE b.id = reading_strategy_annotations.book_id AND b.status = 'active'));
REVOKE ALL PRIVILEGES ON TABLE public.reading_strategy_detail FROM anon, authenticated;
ALTER TABLE public.reading_strategy_detail ENABLE ROW LEVEL SECURITY;
DROP POLICY "public read" ON public.reading_strategy_detail;
GRANT SELECT ON TABLE public.reading_strategy_detail TO anon, authenticated;
CREATE POLICY "pilot trusted read" ON public.reading_strategy_detail FOR SELECT TO anon, authenticated USING (true);
REVOKE ALL PRIVILEGES ON TABLE public.teaching_ideas FROM anon, authenticated;
ALTER TABLE public.teaching_ideas ENABLE ROW LEVEL SECURITY;
DROP POLICY "public read" ON public.teaching_ideas;
GRANT SELECT ON TABLE public.teaching_ideas TO anon, authenticated;
CREATE POLICY "pilot trusted read" ON public.teaching_ideas FOR SELECT TO anon, authenticated USING (status IN ('teacher_reviewed','teacher_added') AND EXISTS (SELECT 1 FROM public.books b WHERE b.id = teaching_ideas.book_id AND b.status = 'active'));
REVOKE ALL PRIVILEGES ON TABLE public.teaching_resources FROM anon, authenticated;
ALTER TABLE public.teaching_resources ENABLE ROW LEVEL SECURITY;
DROP POLICY "public read" ON public.teaching_resources;
REVOKE ALL PRIVILEGES ON TABLE public.why_use_bullets FROM anon, authenticated;
ALTER TABLE public.why_use_bullets ENABLE ROW LEVEL SECURITY;
DROP POLICY "public read" ON public.why_use_bullets;
GRANT SELECT ON TABLE public.why_use_bullets TO anon, authenticated;
CREATE POLICY "pilot trusted read" ON public.why_use_bullets FOR SELECT TO anon, authenticated USING (status IN ('teacher_reviewed','teacher_added') AND EXISTS (SELECT 1 FROM public.books b WHERE b.id = why_use_bullets.book_id AND b.status = 'active'));
REVOKE ALL PRIVILEGES ON TABLE public.writing_trait_annotations FROM anon, authenticated;
ALTER TABLE public.writing_trait_annotations ENABLE ROW LEVEL SECURITY;
DROP POLICY "public read" ON public.writing_trait_annotations;
GRANT SELECT ON TABLE public.writing_trait_annotations TO anon, authenticated;
CREATE POLICY "pilot trusted read" ON public.writing_trait_annotations FOR SELECT TO anon, authenticated USING (status IN ('imported_teacher','imported_ozlit','teacher_reviewed','teacher_added') AND EXISTS (SELECT 1 FROM public.books b WHERE b.id = writing_trait_annotations.book_id AND b.status = 'active'));
REVOKE ALL PRIVILEGES ON TABLE public.writing_trait_detail FROM anon, authenticated;
ALTER TABLE public.writing_trait_detail ENABLE ROW LEVEL SECURITY;
DROP POLICY "public read" ON public.writing_trait_detail;
GRANT SELECT ON TABLE public.writing_trait_detail TO anon, authenticated;
CREATE POLICY "pilot trusted read" ON public.writing_trait_detail FOR SELECT TO anon, authenticated USING (true);
REVOKE ALL PRIVILEGES ON TABLE public.writing_traits FROM anon, authenticated;
ALTER TABLE public.writing_traits ENABLE ROW LEVEL SECURITY;
DROP POLICY "public read" ON public.writing_traits;
GRANT SELECT ON TABLE public.writing_traits TO anon, authenticated;
CREATE POLICY "pilot trusted read" ON public.writing_traits FOR SELECT TO anon, authenticated USING (true);
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated;
COMMIT;
