-- Restores the observed pre-change public access; use only to reverse this exact change.
BEGIN;
DROP POLICY IF EXISTS "pilot trusted read" ON public.books;
GRANT ALL PRIVILEGES ON TABLE public.books TO anon, authenticated;
CREATE POLICY "public read" ON public.books FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "pilot trusted read" ON public.inquiry_lens_annotations;
GRANT ALL PRIVILEGES ON TABLE public.inquiry_lens_annotations TO anon, authenticated;
CREATE POLICY "public read" ON public.inquiry_lens_annotations FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "pilot trusted read" ON public.inquiry_lenses;
GRANT ALL PRIVILEGES ON TABLE public.inquiry_lenses TO anon, authenticated;
CREATE POLICY "public read" ON public.inquiry_lenses FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "pilot trusted read" ON public.pride_value_annotations;
GRANT ALL PRIVILEGES ON TABLE public.pride_value_annotations TO anon, authenticated;
CREATE POLICY "public read" ON public.pride_value_annotations FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "pilot trusted read" ON public.pride_values;
GRANT ALL PRIVILEGES ON TABLE public.pride_values TO anon, authenticated;
CREATE POLICY "public read" ON public.pride_values FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "pilot trusted read" ON public.reading_strategies;
GRANT ALL PRIVILEGES ON TABLE public.reading_strategies TO anon, authenticated;
CREATE POLICY "public read" ON public.reading_strategies FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "pilot trusted read" ON public.reading_strategy_annotations;
GRANT ALL PRIVILEGES ON TABLE public.reading_strategy_annotations TO anon, authenticated;
CREATE POLICY "public read" ON public.reading_strategy_annotations FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "pilot trusted read" ON public.reading_strategy_detail;
GRANT ALL PRIVILEGES ON TABLE public.reading_strategy_detail TO anon, authenticated;
CREATE POLICY "public read" ON public.reading_strategy_detail FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "pilot trusted read" ON public.teaching_ideas;
GRANT ALL PRIVILEGES ON TABLE public.teaching_ideas TO anon, authenticated;
CREATE POLICY "public read" ON public.teaching_ideas FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "pilot trusted read" ON public.teaching_resources;
GRANT ALL PRIVILEGES ON TABLE public.teaching_resources TO anon, authenticated;
CREATE POLICY "public read" ON public.teaching_resources FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "pilot trusted read" ON public.why_use_bullets;
GRANT ALL PRIVILEGES ON TABLE public.why_use_bullets TO anon, authenticated;
CREATE POLICY "public read" ON public.why_use_bullets FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "pilot trusted read" ON public.writing_trait_annotations;
GRANT ALL PRIVILEGES ON TABLE public.writing_trait_annotations TO anon, authenticated;
CREATE POLICY "public read" ON public.writing_trait_annotations FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "pilot trusted read" ON public.writing_trait_detail;
GRANT ALL PRIVILEGES ON TABLE public.writing_trait_detail TO anon, authenticated;
CREATE POLICY "public read" ON public.writing_trait_detail FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "pilot trusted read" ON public.writing_traits;
GRANT ALL PRIVILEGES ON TABLE public.writing_traits TO anon, authenticated;
CREATE POLICY "public read" ON public.writing_traits FOR SELECT TO public USING (true);
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated;
COMMIT;
