'use strict';
const $=id=>document.getElementById(id), groups=['writing','reading','pride','inquiry'];
const titles={writing:'Writing purposes',reading:'Reading purposes',pride:'PRIDE values',inquiry:'Inquiry lenses'};
let data, covers={}, lastFocus;
const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const hasText=x=>typeof x==='string'&&x.trim().length>0;
const allLinks=b=>groups.flatMap(g=>b[g]);
function image(b){if(!covers[b.id])return node('div','No cover available','cover placeholder');const img=node('img',undefined,'cover');img.src='/covers/'+encodeURIComponent(b.cover_url);img.alt='Cover of '+b.title;img.loading='lazy';img.addEventListener('error',()=>{covers[b.id]=false;img.replaceWith(node('div','Cover unavailable','cover placeholder'));});return img;}
function badge(text,cls){return node('span',text,'badge '+cls);}
function label(g,slug){return data.references[g].find(x=>x.slug===slug)?.name||slug||'Unlabelled connection';}
function filtered(){const q=$('search').value.trim().toLocaleLowerCase();return data.books.filter(b=>{
if(q&&!`${b.title} ${b.author||''}`.toLocaleLowerCase().includes(q))return false;
for(const g of groups){const value=$(g).value;if(value==='any'&&!b[g].length)return false;if(value==='none'&&b[g].length)return false;if(value&&value!=='any'&&value!=='none'&&!b[g].some(a=>a.slug===value))return false;}
const links=allLinks(b), purposes=b.writing.length+b.reading.length;
return ({'':true,cover:!!covers[b.id],'no-cover':!covers[b.id],blurb:hasText(b.blurb),'no-blurb':!hasText(b.blurb),purposes:purposes>0,'no-purposes':!purposes,explanation:links.some(a=>hasText(a.text)),'needs-explanation':links.length>0&&links.some(a=>!hasText(a.text))})[$('availability').value];});}
function render(){const books=filtered();$('count').textContent=`${books.length} of ${data.books.length} books`;$('results').replaceChildren();
if(!books.length){const box=node('div',undefined,'empty');box.append(node('h3','No books match these filters.'),node('p',"Try clearing a filter. No PRIDE or inquiry links have been recorded yet; this does not mean the books cannot support those connections."));$('results').append(box);return;}
const frag=document.createDocumentFragment();for(const b of books){const card=node('button',undefined,'book');card.setAttribute('aria-label','View '+b.title);const top=node('div',undefined,'book-top'),info=node('div');info.append(node('h3',b.title),node('p',b.author||'Author not recorded','author'));top.append(image(b),info);card.append(top);const tags=node('div',undefined,'badges');for(const g of groups)tags.append(badge(`${g==='pride'?'PRIDE':g[0].toUpperCase()+g.slice(1)} · ${b[g].length}`,b[g].length?g:'missing'));card.append(tags,node('p',`${hasText(b.blurb)?'Blurb recorded':'Blurb missing'} · ${covers[b.id]?'Cover available':'Cover missing'}`,'small'));const total=allLinks(b).length,explained=allLinks(b).filter(a=>hasText(a.text)).length;card.append(node('p',total?`${explained} of ${total} connections have explanations`:'No teaching connections recorded','small'));card.onclick=()=>openBook(b,card);frag.append(card);}$('results').append(frag);}
function openBook(b,trigger){lastFocus=trigger;const content=$('detail-content');content.replaceChildren();const hero=node('div',undefined,'detail-hero'),heading=node('div');heading.append(node('h2',b.title),node('p',b.author||'Author not recorded'));if(b.illustrator)heading.append(node('p','Illustrated by '+b.illustrator,'small'));hero.append(image(b),heading);content.append(hero);
const meta=node('div',undefined,'meta');meta.append(badge(b.text_type||'Text type not recorded','missing'),badge(b.genre||'Genre not recorded','missing'));content.append(meta);
const blurb=node('section',undefined,'detail-section');blurb.append(node('h3','Blurb'),node('p',b.blurb||'No blurb recorded.','blurb'));if(b.blurb)blurb.append(node('p','Recorded status: '+(b.blurb_status||'Not recorded'),'small'));content.append(blurb);
for(const g of groups){const section=node('section',undefined,'detail-section');section.append(node('h3',`${titles[g]} (${b[g].length})`));if(!b[g].length)section.append(node('p','No connections recorded yet.','small'));for(const a of b[g]){const entry=node('div',undefined,'entry');entry.append(badge(label(g,a.slug),g),node('p',hasText(a.text)?a.text:'Purpose recorded. The book-specific teaching explanation has not been added yet.'));const status={'imported_teacher':'Imported teacher selection','imported_ozlit':'Imported OzLit selection','reviewed_added':'Reviewed addition'}[a.status]||a.status||'Not recorded';entry.append(node('p',`Source: ${a.source||'Not recorded'} · Status: ${status}${a.years?' · Years: '+a.years:''}`,'small'));section.append(entry);}content.append(section);}
const ideas=node('section',undefined,'detail-section');ideas.append(node('h3',`Teaching ideas (${b.teaching_ideas.length})`),node('p',b.teaching_ideas.length?'Teaching idea records exist in this snapshot.':'No teaching ideas recorded yet.','small'));content.append(ideas);$('detail').showModal();$('close').focus();}
$('close').onclick=()=>$('detail').close();$('detail').addEventListener('close',()=>lastFocus?.focus());
for(const id of ['search',...groups,'availability'])$(id).addEventListener(id==='search'?'input':'change',()=>data&&render());
$('reset').onclick=()=>{for(const id of ['search',...groups,'availability'])$(id).value='';render();};
async function init(){try{const [res,cr]=await Promise.all([fetch('data.json'),fetch('cover-status.json')]);if(!res.ok||!cr.ok)throw Error('Snapshot unavailable');data=await res.json();covers=await cr.json();$('snapshot').textContent='Read-only snapshot · Checked '+new Date(data.checked_at).toLocaleString('en-AU',{dateStyle:'medium',timeStyle:'short'})+' · Ask to refresh after database changes.';
for(const g of groups){const select=$(g);select.append(new Option('All books',''),new Option('Has any recorded connection','any'),new Option('No connections recorded','none'));for(const ref of data.references[g]){const count=data.books.filter(b=>b[g].some(a=>a.slug===ref.slug)).length;select.append(new Option(`${ref.name} (${count})`,ref.slug));}}
const stats=[['Books',data.books.length],['With writing purposes',data.books.filter(b=>b.writing.length).length],['With reading purposes',data.books.filter(b=>b.reading.length).length],['With PRIDE values',data.books.filter(b=>b.pride.length).length],['With inquiry lenses',data.books.filter(b=>b.inquiry.length).length]];for(const [label,value] of stats){const el=node('div',undefined,'stat');el.append(node('strong',String(value)),node('span',label));$('stats').append(el);}render();}catch(e){$('count').textContent='Catalogue could not be loaded';$('snapshot').textContent='Please restart the catalogue viewer server and reload.';$('results').append(node('p','The viewer needs its data.json file and local cover service.'));}}
init();
